---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: Infórmate sobre los cambios más recientes en las funciones y los servicios de datos que forman parte de la implementación local de la NetApp Console. 
---
= Cambios recientes en la implementación local de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Infórmate sobre los cambios más recientes en las funciones y los servicios de datos que forman parte de la implementación local de NetApp Console.



[[10-august-2026]]
== 10 de agosto de 2026



[[netapp-console-local-deployment]]
=== NetApp Console implementación local



==== Presentación de la implementación local de NetApp Console

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["Aprende a implementar localmente la NetApp Console"].



[[backup-and-recovery]]
=== Backup and Recovery



==== Mejoras generales de NetApp Backup and Recovery

* *Compatibilidad con la implementación local de NetApp Console*: Esta versión de NetApp Backup and Recovery es compatible con la implementación local de NetApp Console en estado de vista previa.
* *90 días de retención de trabajos*: Backup and Recovery ahora conserva la información de los trabajos en el Monitor de trabajos durante 90 días.




==== Mejoras en las cargas de trabajo de VMware

En esta versión, VMware workloads introduce las siguientes mejoras:

* *Compatibilidad con la restauración en una ubicación alternativa para SAN VMs*: Ahora puedes restaurar copias de seguridad de SAN VMs en una ubicación alternativa.
* *Compatibilidad con la eliminación de varias copias de seguridad*: Ahora puedes eliminar varias copias de seguridad a la vez.


Para obtener detalles sobre cómo proteger las cargas de trabajo de VMware, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Descripción general de la protección de cargas de trabajo de VMware"].



==== Mejoras en cargas de trabajo de Kubernetes

En esta versión, las cargas de trabajo de Kubernetes introducen las siguientes mejoras:

* *Compatibilidad en versión preliminar con recursos aislados físicamente*: Si ejecutas NetApp Backup and Recovery en una implementación local de NetApp Console, puedes descubrir, proteger y restaurar recursos de Kubernetes aislados físicamente. Esta función está en versión preliminar para este lanzamiento.


Para obtener más información sobre cómo proteger las cargas de trabajo de Kubernetes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Descripción general de la protección de cargas de trabajo de Kubernetes"].



==== Mejoras en las cargas de trabajo de ONTAP Volumes

En esta versión, las cargas de trabajo de ONTAP Volumes incorporan las siguientes mejoras:

* *Dar prioridad a las tareas de restauración frente a las de copia de seguridad*: Ahora puedes dar prioridad a las tareas de restauración frente a las de copia de seguridad al restaurar máquinas virtuales o archivos.
* *Detectar sistemas y volúmenes ONTAP sin activar Backup and Recovery*: Ahora puedes detectar sistemas y volúmenes sin activar Backup and Recovery.


Para obtener más información sobre la protección de las cargas de trabajo de ONTAP Volumes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Descripción general de la protección de cargas de trabajo de ONTAP Volumes"].



[[13-july-2026]]
== 13 de julio de 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Compatibilidad mejorada con múltiples compartimentos para todas las cargas de trabajo

NetApp Backup and Recovery ahora permite proteger las cargas de trabajo dentro de un sistema con hasta 100 buckets repartidos entre diferentes proveedores de nube. Se requiere ONTAP 9.19.1 o una versión posterior para admitir más de 6 buckets por sistema.

Para obtener más información sobre NetApp Backup and Recovery, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Obtén información sobre NetApp Backup and Recovery"].



[[15-june-2026]]
== 15 de junio de 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Mejoras en cargas de trabajo de Kubernetes

En esta versión, las cargas de trabajo de Kubernetes introducen las siguientes mejoras:

* *Trident Protect 26.06*: Esta versión incluye Trident Protect 26.06.
* *Omitir la creación de aplicaciones durante la restauración*: Ahora puedes omitir la creación automática de objetos de recursos personalizados de aplicaciones durante las operaciones de restauración. Esto reduce las entradas innecesarias en el inventario de la aplicación.
* *Restaurar reclamaciones de volúmenes persistentes de máquinas virtuales*: Al restaurar aplicaciones basadas en máquinas virtuales, ahora puedes restaurar reclamaciones de volúmenes persistentes individuales sin restaurar toda la máquina virtual, lo que hace que la recuperación sea más rápida cuando discos o volúmenes específicos se ven afectados por corrupción o pérdida de datos.
* *Mejoras en el monitor de tareas*: El monitor de tareas ahora ofrece una mayor visibilidad de las tareas de protección de Kubernetes. Puedes consultar información detallada sobre el estado de las tareas y subtareas, y ver el almacenamiento de destino que utiliza cada una.


Para obtener más información sobre cómo proteger las cargas de trabajo de Kubernetes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Descripción general de la protección de cargas de trabajo de Kubernetes"].



[[08-june-2026]]
== 8 de junio de 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Mejoras en las cargas de trabajo de ONTAP Volumes

En esta versión, las cargas de trabajo de ONTAP Volumes introducen la siguiente mejora:

*Soporte para almacenamiento en la nube compatible con S3*: NetApp Backup and Recovery para cargas de trabajo de Volumes ahora admite la realización de copias de seguridad en almacenamiento en la nube compatible con S3.

Para obtener más información sobre la protección de las cargas de trabajo de ONTAP Volumes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Descripción general de la protección de cargas de trabajo de ONTAP Volumes"].



==== Mejoras en las cargas de trabajo de Hyper-V

En esta versión, las cargas de trabajo Hyper-V introducen las siguientes mejoras:

* *Mejoras en la restauración de archivos y carpetas en una máquina virtual invitada*: Ahora puedes restaurar archivos y carpetas de una instantánea en el almacenamiento primario o secundario a una máquina virtual de Windows invitada. Esta función ahora es compatible con VMs CIFS y SAN.
* *Los grupos de protección ahora utilizan la programación basada en la zona horaria del host*: Los grupos de protección ahora utilizan la zona horaria del host de Hyper-V. Los grupos de protección creados antes de que se introdujera la programación basada en la zona horaria del host siguen utilizando la hora configurada anteriormente (normalmente UTC). Para actualizar estos grupos de protección y que utilicen la zona horaria del host de Hyper-V, tienes que volver a crear las programaciones. Consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Crear y gestionar grupos de protección para cargas de trabajo de Hyper-V"] para más información.


Para más detalles sobre la protección de cargas de trabajo Hyper-V, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Flujo de trabajo de protección de Hyper-V con NetApp Backup and Recovery"].



==== Mejoras en las cargas de trabajo de VMware

En esta versión, VMware workloads introduce la siguiente mejora:

* *Los grupos de protección ahora utilizan la programación basada en la zona horaria del host*: Los grupos de protección ahora utilizan la zona horaria del servidor VMware vCenter que los aloja. Los grupos de protección creados antes de que se introdujera la programación basada en la zona horaria del host siguen ejecutándose en la zona horaria configurada anteriormente (normalmente UTC). Para usar la zona horaria de vCenter, tienes que volver a crear las programaciones. Consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Crear y gestionar grupos de protección para cargas de trabajo de VMware"] para más información.


Para obtener detalles sobre cómo proteger las cargas de trabajo de VMware, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Descripción general de la protección de cargas de trabajo de VMware"].
