---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: Infórmate sobre los cambios más recientes en las funciones y los servicios de datos que forman parte de la implementación local de la NetApp Console. 
---
= Cambios recientes en la implementación local de NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Infórmate sobre los cambios más recientes en las funciones y los servicios de datos que forman parte de la implementación local de NetApp Console.



[[16-september-2026]]
== 16 de septiembre de 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Mejoras generales de NetApp Backup and Recovery

En esta versión, las cargas de trabajo de KVM, Hyper-V y VMware incorporan la siguiente mejora:

*Selección de credenciales durante la detección de hosts de máquinas virtuales*: Al registrar un host KVM, Hyper-V o VMware, ahora puedes utilizar las credenciales que ya hayas añadido a Backup and Recovery.



==== Mejoras en las cargas de trabajo de Hyper-V

En esta versión, las cargas de trabajo de Hyper-V incorporan la siguiente mejora:

*Protección de discos distribuidos para máquinas virtuales*: En las configuraciones CIFS, NetApp Backup and Recovery ahora permite proteger todos los discos conectados a cada máquina virtual de un grupo de protección. Esto incluye tanto los archivos distribuidos en varios volúmenes ONTAP o sistemas de almacenamiento ONTAP (discos distribuidos) como los archivos que se encuentran en una única ubicación.

Para más detalles sobre la protección de cargas de trabajo Hyper-V, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Aprende a proteger las cargas de trabajo de Hyper-V con NetApp Backup and Recovery"].



==== Mejora del rendimiento de las cargas de trabajo de los volúmenes ONTAP

En esta versión, las cargas de trabajo de ONTAP Volumes incorporan la siguiente mejora en fase de prueba:

*Informe diario de transferencia de datos de copia de seguridad*: NetApp Backup and Recovery for Volumes incluye ahora un informe diario de transferencia de datos de copia de seguridad en la pestaña "Informes", lo que te permite conocer la actividad diaria de transferencia de datos de copia de seguridad y replicación en todo tu entorno. Puedes generar el informe para toda la cuenta o para sistemas de almacenamiento seleccionados, filtrarlo por intervalo de fechas y tipo de protección, y descargar los resultados en formato CSV.

Para obtener más información sobre la protección de las cargas de trabajo de ONTAP Volumes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Descubre la protección de volúmenes de ONTAP con NetApp Backup and Recovery"].



[[17-august-2026]]
== 17 de agosto de 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Mejoras en las cargas de trabajo de Hyper-V

En esta versión, las cargas de trabajo de Hyper-V incorporan la siguiente mejora:

*Restaurar una copia de seguridad del almacenamiento de objetos en una ubicación alternativa*: Ahora puedes restaurar máquinas virtuales de Hyper-V, archivos y carpetas desde el almacenamiento de objetos a una ubicación de almacenamiento alternativa.

Para más detalles sobre la protección de cargas de trabajo Hyper-V, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Aprende a proteger las cargas de trabajo de Hyper-V con NetApp Backup and Recovery"].



==== Mejoras en cargas de trabajo de Kubernetes

En esta versión, las cargas de trabajo de Kubernetes introducen las siguientes mejoras:

* *Trident Protect 26.08*: Esta versión incluye Trident Protect 26.08.
* *Reintentos de copia de seguridad*: Ahora puedes activar los reintentos de copia de seguridad y configurar el número de intentos y los intervalos entre ellos como ajustes avanzados en las políticas de protección de Kubernetes.
* *Éxito parcial del backup*: Ahora puedes configurar ajustes avanzados en las políticas de protección de Kubernetes para que el backup continúe cuando fallen recursos individuales, permitiendo que las tareas de backup se completen como parcialmente exitosas. Esto te permite restaurar los recursos respaldados incluso si algunos recursos fallan durante la operación de backup.
* *Copias de seguridad coherentes con los fallos y coherentes con la máquina virtual*: El servicio NetApp Backup and Recovery for NetApp Console ahora permite configurar políticas de protección que crean copias de seguridad o instantáneas coherentes con los fallos o coherentes con la máquina virtual. También puedes personalizar cómo se realizan las congelaciones de la máquina virtual durante la operación de protección.
* *Volver a conectar el clúster de Kubernetes tras un cambio de IP del agente de Console*: el servicio Backup and Recovery para NetApp Console ahora te permite volver a conectar un clúster a su agente de Console si la dirección IP del agente cambia.
* *Migra el clúster a un nuevo agente de Console*: el servicio Backup and Recovery for NetApp Console ahora te permite migrar un clúster a un nuevo agente de Console si el agente original falla o se elimina, lo que garantiza una protección de aplicaciones sin interrupciones.


Para obtener más información sobre cómo proteger las cargas de trabajo de Kubernetes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Descubre cómo proteger las cargas de trabajo de Kubernetes con NetApp Backup and Recovery"].



==== Mejora de las cargas de trabajo de Oracle Database

En esta versión, las cargas de trabajo de Oracle Database introducen las siguientes mejoras:

* *Restauración de bases de datos conectables (PDB)*: ahora puedes restaurar bases de datos conectables (PDB) y espacios de tabla de PDB de forma individual, incluida la recuperación a un momento específico.
* *Clon de una base de datos conectable (PDB)*: ahora puedes clonar una sola PDB en una base de datos contenedora (CDB) de destino ya existente y, si quieres, excluir PDBs cuando clones una base de datos contenedora completa.


Para obtener detalles sobre cómo proteger las cargas de trabajo de Oracle Database, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Descubre cómo proteger las cargas de trabajo de Oracle Database con NetApp Backup and Recovery"].



[[10-august-2026]]
== 10 de agosto de 2026



[[netapp-console-local-deployment]]
=== NetApp Console implementación local



==== Presentación de la implementación local de NetApp Console

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["Aprende a implementar localmente la NetApp Console"].

https://docs.netapp.com/us-en/console-local/console-differences.html["Descubre las diferencias entre la implementación local de NetApp Console y NetApp Console SaaS y modo privado"].



[[backup-and-recovery]]
=== Backup and Recovery



==== Mejoras generales de NetApp Backup and Recovery

* *Compatibilidad con la implementación local de NetApp Console*: Esta versión de NetApp Backup and Recovery es compatible con la implementación local de NetApp Console en estado de vista previa.
* *90 días de retención de trabajos*: Backup and Recovery ahora conserva la información de los trabajos en el Monitor de trabajos durante 90 días.




==== Mejoras en las cargas de trabajo de VMware

En esta versión, VMware workloads introduce las siguientes mejoras:

* *Compatibilidad con la restauración en una ubicación alternativa para SAN VMs*: Ahora puedes restaurar copias de seguridad de SAN VMs en una ubicación alternativa.
* *Compatibilidad con la eliminación de varias copias de seguridad*: Ahora puedes eliminar varias copias de seguridad a la vez.


Para obtener detalles sobre cómo proteger las cargas de trabajo de VMware, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Descripción general de la protección de cargas de trabajo de VMware"].



==== Mejoras en cargas de trabajo de Kubernetes

En esta versión, las cargas de trabajo de Kubernetes introducen las siguientes mejoras:

* *Compatibilidad en versión preliminar con recursos aislados físicamente*: Si ejecutas NetApp Backup and Recovery en una implementación local de NetApp Console, puedes descubrir, proteger y restaurar recursos de Kubernetes aislados físicamente. Esta función está en versión preliminar para este lanzamiento.


Para obtener más información sobre cómo proteger las cargas de trabajo de Kubernetes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Descripción general de la protección de cargas de trabajo de Kubernetes"].



==== Mejoras en las cargas de trabajo de ONTAP Volumes

En esta versión, las cargas de trabajo de ONTAP Volumes incorporan las siguientes mejoras:

* *Dar prioridad a las tareas de restauración frente a las de copia de seguridad*: Ahora puedes dar prioridad a las tareas de restauración frente a las de copia de seguridad al restaurar máquinas virtuales o archivos.
* *Detectar sistemas y volúmenes ONTAP sin activar Backup and Recovery*: Ahora puedes detectar sistemas y volúmenes sin activar Backup and Recovery.


Para obtener más información sobre la protección de las cargas de trabajo de ONTAP Volumes, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Descripción general de la protección de cargas de trabajo de ONTAP Volumes"].



[[13-july-2026]]
== 13 de julio de 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Compatibilidad mejorada con múltiples compartimentos para todas las cargas de trabajo

NetApp Backup and Recovery ahora permite proteger las cargas de trabajo dentro de un sistema con hasta 100 buckets repartidos entre diferentes proveedores de nube. Se requiere ONTAP 9.19.1 o una versión posterior para admitir más de 6 buckets por sistema.

Para obtener más información sobre NetApp Backup and Recovery, consulta https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Obtén información sobre NetApp Backup and Recovery"].
